-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	desert_eagle = "rbxassetid://6048706726",
	g19 = "rbxassetid://6048706785",
	m249 = "rbxassetid://6048706837",
	m4a1 = "rbxassetid://6048706895",
	["pp-19_bizon"] = "rbxassetid://6048706955",
	ump45 = "rbxassetid://6048707006",
}