name = "Assets"

[[inputs]]
glob = "assets/**/*.png" # location & file type of assets
codegen = true
codegen-path = "src/ReplicatedStorage/assets.lua" # location of modules holding loaded assets
codegen-base-path = "assets"